### ISSUE TITLE
La première ligne des fichiers chargés est décalée vers la gauche de 1

### ISSUE THREAD

**Issue by SathanBERNARD** [LoupLobet/px212#1]
La première ligne des fichiers chargés est décalée vers la gauche de 1, loader ou display?

**Comment by LoupLobet** [comment]
comment ça ?

**Comment by SathanBERNARD** [comment]
ça le fait pas avec les maps que je génere mais j'ai pas eu le tps d'investiguer plus

**Comment by LoupLobet** [comment]
je comprends pas du tout le problème que tu décrit, quand tu charge un fichier avec le loadmap() la première ligne est décalé à gauche ?

**Comment by SathanBERNARD** [comment]
je vais au resto donc on verra après
![Screenshot from 2022-06-04 19-48-08](https://user-images.githubusercontent.com/106816227/172019506-776bfab7-9da2-4816-bf47-0d12fbca04b8.png)

**Comment by LoupLobet** [comment]
effectivement c'est étrange, de mon coté je n'ai pas de problème de ce genre quand j'affiche une map. Est ce que ce ne viendrais pas de spacetochar() (je vois des '!' dans la map, qui pourraient venir de char c = '!';)

**Comment by thonyan32** [comment]
Je n'ai aucun problème non plus avec le loader de loup

**Comment by SathanBERNARD** [comment]
Sauf erreur de ma part, lorsque le premier while se termine par un caractère non ';' ce caractère, qui est le premier de la map, n'est pas pris en compte dans le second while.

![image](https://user-images.githubusercontent.com/106816227/172024719-3ef380ea-3c89-418a-a2e0-1d45c628c0fc.png)

**Comment by LoupLobet** [comment]
Oui en effet, je règle ça de suite

**Comment by LoupLobet** [comment]
c'est réglé @SathanBERNARD
